services:
  frontend:
    image: nginx:1.20-alpine
    build:
      context: ./frontend/
    volumes:
      - ./frontend/build/:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: taivuttaja-frontend
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    container_name: taivuttaja-backend
    ports:
      - 3001:3001
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
