services:
  frontend:
    image: nginx:1.20-alpine
    build:
      context: ./frontend/
    volumes:
      - ./frontend/build/:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: taivuttaja-frontend
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/:/docker-entrypoint-initdb.d/
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    container_name: taivuttaja-backend
    ports:
      - 3001:3001
    extra_hosts:
        - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
