GET http://localhost:3001/api/words/random
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MjJhMGFiYzI5ZDRlYTA0OWE1YmNkNmUiLCJpYXQiOjE2NDcwMjI3MjQsImV4cCI6MTY0NzAyNjMyNH0.yGkCka_9YPBjjNPztEU86rGG6pdWnPgX7DWg59XV9Tk