name: Deploy

on:
  push:
    branches:
      - main

    
jobs:
  deploy_to_server:
    if: ${{!contains(join(toJson(github.event.commits.*.message)), '#skip') }} 
    timeout-minutes: 45
    runs-on: ubuntu-20.04
    needs: run_all_tests
    
    steps:

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd ~/taivuttaja_deploy/taivuttaja
            git pull
            docker compose -f docker-compose.yml down --volumes
            docker compose -f docker-compose.yml up -d
